spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbfelipemusic?
    useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: battlefield1942
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
    hibernate:
    show_sql: true
    hbm2ddl:
    auto: update